import { describe, expect, test } from 'bun:test';
import { MiniMenuAction } from '#/client/MiniMenuAction.js';

describe('MiniMenuAction literals (regression / upstream merge)', () => {
    test('matches expected opcode table', () => {
        expect(MiniMenuAction._PRIORITY).toBe(2000);
        expect(MiniMenuAction.TGT_LOC).toBe(899);
        expect(MiniMenuAction.OP_LOC1).toBe(625);
        expect(MiniMenuAction.OP_LOC2).toBe(721);
        expect(MiniMenuAction.OP_LOC3).toBe(743);
        expect(MiniMenuAction.OP_LOC4).toBe(357);
        expect(MiniMenuAction.OP_LOC5).toBe(1071);
        expect(MiniMenuAction.USEHELD_ONLOC).toBe(810);
        expect(MiniMenuAction.TGT_NPC).toBe(240);
        expect(MiniMenuAction.OP_NPC1).toBe(242);
        expect(MiniMenuAction.OP_NPC2).toBe(209);
        expect(MiniMenuAction.OP_NPC3).toBe(309);
        expect(MiniMenuAction.OP_NPC4).toBe(852);
        expect(MiniMenuAction.OP_NPC5).toBe(793);
        expect(MiniMenuAction.USEHELD_ONNPC).toBe(829);
        expect(MiniMenuAction.TGT_OBJ).toBe(370);
        expect(MiniMenuAction.OP_OBJ1).toBe(139);
        expect(MiniMenuAction.OP_OBJ2).toBe(778);
        expect(MiniMenuAction.OP_OBJ3).toBe(617);
        expect(MiniMenuAction.OP_OBJ4).toBe(224);
        expect(MiniMenuAction.OP_OBJ5).toBe(662);
        expect(MiniMenuAction.USEHELD_ONOBJ).toBe(111);
        expect(MiniMenuAction.TGT_PLAYER).toBe(131);
        expect(MiniMenuAction.OP_PLAYER1).toBe(639);
        expect(MiniMenuAction.ACCEPT_DUELREQ).toBe(957);
        expect(MiniMenuAction.OP_PLAYER2).toBe(499);
        expect(MiniMenuAction.OP_PLAYER3).toBe(27);
        expect(MiniMenuAction.OP_PLAYER4).toBe(387);
        expect(MiniMenuAction.ACCEPT_TRADEREQ).toBe(507);
        expect(MiniMenuAction.OP_PLAYER5).toBe(185);
        expect(MiniMenuAction.USEHELD_ONPLAYER).toBe(275);
        expect(MiniMenuAction.TGT_HELD).toBe(563);
        expect(MiniMenuAction.OP_HELD1).toBe(694);
        expect(MiniMenuAction.OP_HELD2).toBe(962);
        expect(MiniMenuAction.OP_HELD3).toBe(795);
        expect(MiniMenuAction.OP_HELD4).toBe(681);
        expect(MiniMenuAction.OP_HELD5).toBe(100);
        expect(MiniMenuAction.USEHELD_ONHELD).toBe(398);
        expect(MiniMenuAction.INV_BUTTON1).toBe(582);
        expect(MiniMenuAction.INV_BUTTON2).toBe(113);
        expect(MiniMenuAction.INV_BUTTON3).toBe(555);
        expect(MiniMenuAction.INV_BUTTON4).toBe(331);
        expect(MiniMenuAction.INV_BUTTON5).toBe(354);
        expect(MiniMenuAction.WALK).toBe(718);
        expect(MiniMenuAction.IF_BUTTON).toBe(231);
        expect(MiniMenuAction.TGT_BUTTON).toBe(274);
        expect(MiniMenuAction.CLOSE_BUTTON).toBe(737);
        expect(MiniMenuAction.TOGGLE_BUTTON).toBe(435);
        expect(MiniMenuAction.SELECT_BUTTON).toBe(225);
        expect(MiniMenuAction.PAUSE_BUTTON).toBe(997);
        expect(MiniMenuAction.USEHELD_START).toBe(102);
        expect(MiniMenuAction.OP_LOC6).toBe(1381);
        expect(MiniMenuAction.OP_NPC6).toBe(1714);
        expect(MiniMenuAction.OP_OBJ6).toBe(1152);
        expect(MiniMenuAction.OP_HELD6).toBe(1328);
        expect(MiniMenuAction.CANCEL).toBe(1106);
        expect(MiniMenuAction.ABUSE_REPORT).toBe(524);
        expect(MiniMenuAction.FRIENDLIST_ADD).toBe(605);
        expect(MiniMenuAction.IGNORELIST_ADD).toBe(47);
        expect(MiniMenuAction.FRIENDLIST_DEL).toBe(513);
        expect(MiniMenuAction.IGNORELIST_DEL).toBe(884);
        expect(MiniMenuAction.MESSAGE_PRIVATE).toBe(902);
    });

    test('no duplicate numeric values among public actions', () => {
        const values = [
            MiniMenuAction.TGT_LOC,
            MiniMenuAction.OP_LOC1,
            MiniMenuAction.OP_LOC2,
            MiniMenuAction.OP_LOC3,
            MiniMenuAction.OP_LOC4,
            MiniMenuAction.OP_LOC5,
            MiniMenuAction.USEHELD_ONLOC,
            MiniMenuAction.TGT_NPC,
            MiniMenuAction.OP_NPC1,
            MiniMenuAction.OP_NPC2,
            MiniMenuAction.OP_NPC3,
            MiniMenuAction.OP_NPC4,
            MiniMenuAction.OP_NPC5,
            MiniMenuAction.USEHELD_ONNPC,
            MiniMenuAction.TGT_OBJ,
            MiniMenuAction.OP_OBJ1,
            MiniMenuAction.OP_OBJ2,
            MiniMenuAction.OP_OBJ3,
            MiniMenuAction.OP_OBJ4,
            MiniMenuAction.OP_OBJ5,
            MiniMenuAction.USEHELD_ONOBJ,
            MiniMenuAction.TGT_PLAYER,
            MiniMenuAction.OP_PLAYER1,
            MiniMenuAction.ACCEPT_DUELREQ,
            MiniMenuAction.OP_PLAYER2,
            MiniMenuAction.OP_PLAYER3,
            MiniMenuAction.OP_PLAYER4,
            MiniMenuAction.ACCEPT_TRADEREQ,
            MiniMenuAction.OP_PLAYER5,
            MiniMenuAction.USEHELD_ONPLAYER,
            MiniMenuAction.TGT_HELD,
            MiniMenuAction.OP_HELD1,
            MiniMenuAction.OP_HELD2,
            MiniMenuAction.OP_HELD3,
            MiniMenuAction.OP_HELD4,
            MiniMenuAction.OP_HELD5,
            MiniMenuAction.USEHELD_ONHELD,
            MiniMenuAction.INV_BUTTON1,
            MiniMenuAction.INV_BUTTON2,
            MiniMenuAction.INV_BUTTON3,
            MiniMenuAction.INV_BUTTON4,
            MiniMenuAction.INV_BUTTON5,
            MiniMenuAction.WALK,
            MiniMenuAction.IF_BUTTON,
            MiniMenuAction.TGT_BUTTON,
            MiniMenuAction.CLOSE_BUTTON,
            MiniMenuAction.TOGGLE_BUTTON,
            MiniMenuAction.SELECT_BUTTON,
            MiniMenuAction.PAUSE_BUTTON,
            MiniMenuAction.USEHELD_START,
            MiniMenuAction.OP_LOC6,
            MiniMenuAction.OP_NPC6,
            MiniMenuAction.OP_OBJ6,
            MiniMenuAction.OP_HELD6,
            MiniMenuAction.CANCEL,
            MiniMenuAction.ABUSE_REPORT,
            MiniMenuAction.FRIENDLIST_ADD,
            MiniMenuAction.IGNORELIST_ADD,
            MiniMenuAction.FRIENDLIST_DEL,
            MiniMenuAction.IGNORELIST_DEL,
            MiniMenuAction.MESSAGE_PRIVATE
        ];
        const set = new Set(values);
        expect(set.size).toBe(values.length);
    });
});
